@tool
extends RefCounted

const VERSION := "editor-control-v1"

const ACTIONS := [
	"refresh_context",
	"focus_editor",
	"focus_panel",
	"viewport_navigate",
	"open_scene",
	"select_node",
	"inspect_node",
	"get_inspector_context",
	"get_node_deep",
	"get_spatial_bounds",
	"spatial_query",
	"placement_check",
	"capture_multi_view",
	"snap_to_ground",
	"snap_to_grid",
	"open_script",
	"list_resources",
	"inspect_imported_assets",
	"get_class_info",
	"inspect_materials",
	"create_shader_material_for_node",
	"set_shader_parameter",
	"set_shader_texture_parameter",
	"inspect_rendering_effects",
	"set_environment_property",
	"create_particle_effect",
	"set_particle_effect_properties",
	"list_animation_players",
	"inspect_animation",
	"preview_animation",
	"stop_animation_preview",
	"get_diagnostics",
	"clear_diagnostics",
	"set_node_transform",
	"set_node_properties",
	"undo_last_bridge_action",
	"save_scene",
	"save_all_scenes",
	"assign_resource_to_node",
	"create_node_resource",
	"set_resource_properties",
	"place_asset_in_scene",
	"create_node",
	"delete_node",
	"rename_node",
	"reparent_node",
	"duplicate_node",
	"instance_scene",
	"list_signal_connections",
	"connect_signal",
	"disconnect_signal",
	"create_animation_clip",
	"notes_get",
	"notes_append",
	"notes_clear",
	"stop_running_scene",
	"emergency_stop",
	"playtest_input",
	"run_playtest_scenario",
	"editor_batch",
]

const FOCUSABLE_NATIVE_PANELS := [
	"Output",
	"Debugger",
	"Stack Trace",
	"Audio",
	"Animation",
	"Shader Editor",
	"Signal Visualizer",
	"Profiler",
	"Visual Profiler",
	"Monitors",
	"Video RAM",
	"Network Profiler",
	"Inspector",
	"FileSystem",
	"Scene",
	"Import",
]

const SCREENSHOT_ONLY_NATIVE_PANELS := [
	"Output",
	"Debugger",
	"Stack Trace",
	"Profiler",
	"Visual Profiler",
	"Monitors",
	"Video RAM",
	"Network Profiler",
]


static func capabilities(max_batch_actions: int, max_property_changes: int) -> Dictionary:
	return {
		"version": VERSION,
		"request_type": "editor_control",
		"actions": ACTIONS.duplicate(),
		"focusable_native_panels": FOCUSABLE_NATIVE_PANELS.duplicate(),
		"screenshot_only_native_panels": SCREENSHOT_ONLY_NATIVE_PANELS.duplicate(),
		"viewport_navigation": {
			"typed_2d_pan_zoom_reset_supported": true,
			"typed_3d_orbit_zoom_frame_selected_supported": false,
			"typed_3d_unavailable_code": "editor_api_unavailable",
			"fallback": "Use editor_focus/select_node plus capture_viewport_screenshot for 3D visual evidence.",
		},
		"multi_view_capture": {
			"supported": true,
			"request_action": "capture_multi_view",
			"views": ["front", "side", "top", "perspective"],
			"capture_scope": "offscreen_scene_world",
			"mutates_scene": false,
			"requires_visible_display": true,
			"fallback_unavailable_code": "multi_view_capture_unavailable",
		},
		"mutation_model": "undo_redo_unsaved_with_explicit_save",
		"auto_save_supported": false,
		"explicit_save_supported": true,
		"native_output_clear_supported": false,
		"native_output_read_supported": false,
		"native_debugger_read_supported": false,
		"native_panel_limitations_tooltip": "Native Godot panels can be focused, but Output/Debugger/Profiler contents are not scraped through a stable editor API. Use diagnostics_get for Bridge-owned logs or screenshots for visual evidence.",
		"max_batch_actions": max_batch_actions,
		"max_property_changes": max_property_changes,
	}
